### ISSUE TITLE
DMG is damaged

### ISSUE THREAD

**Issue by mrobert-ledger** [GuilhE/JsonBroadcaster#2]
Hi

I have an error message from OSX when I try to open your DMG : 
"JsonBroadcaster.app" is damaged and can't be opened (...)

I figured out a way to start the app : 
- do a "sudo xattr -cr JsonBroadcaster.app" (inside Applications folder)
- start the app normally

Then the broadcast feature doesn't work until your start the desktop app with terminal (and not by double clicking the icon) :
"open /Applications/JsonBroadcaster.app" for example

**Comment by GuilhE** [comment]
Hum... that's strange. I'm running on macOS 13.1 (22C65) and never had that kind of trouble 🤔 
I'm going to try to find out what could be the cause

**Comment by GuilhE** [comment]
I think it could be related with git lfs, I'll install it and ping you back.

**Comment by GuilhE** [comment]
Hello there @mrobert-ledger ! I wanted to follow up regarding the issue you reported. I've been trying to replicate the error you mentioned, but so far, I haven't been successful in doing so. Nevertheless, I wanted to let you know that I've  released a new version. This update might resolve the problem you encountered.
